---
- name: Download PDFReactor
  get_url: 
    url: "{{ PDF_REACTOR_URL }}/{{ PDF_REACTOR_FILE }}"
    dest: "{{ PDF_REACTOR_INSTALL_DIR }}/{{ PDF_REACTOR_FILE }}"
    timeout: 60
    use_proxy: true
    force: false

- name: Untar PDFReactor
  unarchive: 
    src: "{{ PDF_REACTOR_INSTALL_DIR }}/{{ PDF_REACTOR_FILE }}"
    dest: "{{ PDF_REACTOR_INSTALL_DIR }}" 
    copy: no
    creates: "{{ PDF_REACTOR_INSTALL_DIR }}/PDFreactor"

- name: Create pdfreactorwebservice symlink
  file:
    src: "{{ PDF_REACTOR_INSTALL_DIR }}/PDFreactor/bin/pdfreactorwebservice"
    dest: "/etc/init.d/pdfreactorwebservice"
    owner: root
    group: root
    state: link

- name: Start and enable pdfreactor
  service: name=pdfreactorwebservice state=started enabled=yes
